config/routes.rb
Cast::Application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'home'

  resources :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :path, VideoUploader

  def set_success(format, opts)
    self.success = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new video_params

    if @video.save
      FFMPEG::Movie.new(@video.path.path).screenshot("#{Rails.root}/public/thumbs/#{@video.path.identifier!.split('.').first}_thumb.jpg", seek_time: 5)
      redirect_to videos_path, flash: { success: 'Success!' }
    else
      render 'new'
    end
  end

  def destroy
    @video = Video.find_by params[:id]
    @video.destroy
    redirect_to videos_path, flash: { success: 'Success!' }
  end

  def video_params
    params.require(:video).permit(:path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Chromecast Yourself
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css"
    = csrf_meta_tags
  body
    header.container.m-header
      .row
        .col-lg-12.text-center
          h1 Chromecast Yourself by Rémi Delhaye
    = javascript_include_tag "jquery", "data-turbolinks-track" => true
    = javascript_include_tag "jquery_ujs", "data-turbolinks-track" => true
    = yield

app/views/pages/home.html.erb
<div class="m-video padding">
  <div class="container m-video--container">
    <div class="row">
      <div id="media_info" class="col-lg-12">
        <div id="media_subtitle">
        </div>
        <div id="media_desc">
        </div>
      </div>
    </div>
    <div class="row">
      <div id="main_video" class="col-lg-12">
        <div class="imageSub"> <!-- Put Your Image Width -->
           <div class="blackbg" id="playerstatebg">IDLE</div>
           <div class=label id="playerstate">IDLE</div>
            <%- if Video.first %>
              <img src="<%= 'thumbs/' + Video.first.path.identifier!.split('.').first + '_thumb.jpg' %>" alt="" id="video_image">
            <%- else %>
              <h1>Pas de vidéos dans la base !</h1>
            <%- end %>
           <div id="video_image_overlay"></div>
           <video id="video_element">
           </video>
        </div>
        <div id="media_control">
           <div id="play"></div>
           <div id="pause"></div>
           <div id="progress_bg"></div>
           <div id="progress"></div>
           <div id="progress_indicator"></div>
           <div id="fullscreen_expand"></div>
           <div id="fullscreen_collapse"></div>
           <div id="casticonactive"></div>
           <div id="casticonidle"></div>
           <div id="audio_bg"></div>
           <div id="audio_bg_track"></div>
           <div id="audio_indicator"></div>
           <div id="audio_bg_level"></div>
           <div id="audio_on"></div>
           <div id="audio_off"></div>
           <div id="duration">00:00:00</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="m-mainwrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="m-video--under--video">
          <div class="col-lg-8"><div id="media_title"></div></div>
          <div class="col-lg-4 m-video--under--video--manage">
            <%= link_to 'Manage videos', videos_path, class: 'btn-block' %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div id="carousel" class="col-lg-12">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="m-mainwrapper--footer--top">
          <h2>Chromecast Yourself</h2>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-4 m-footer--container">
        <h3 class="m-footer--title">Navigation</h3>
        <p class="m-footer--p">
          <%= link_to 'Manage videos', videos_path %>
          <%= link_to 'Add a new video', new_video_path %>
        </p>
      </div>
      <div class="col-lg-4 m-footer--container">
        <h3 class="m-footer--title">About</h3>
        <p class="m-footer--p">
          With <span class="white">Chromecastyourself</span>, you can stream easily all your .mp4 videos on your Google's Chromecast using the power of <span class="white">Ruby on Rails</span>.
        </p>
      </div>
      <div class="col-lg-4 m-footer--container">
        <h3 class="m-footer--title">Be social</h3>
        <p class="m-footer--p">
          <a href="#">Facebook</a>
          <a href="#">Twitter</a>
          <a href="#">Github</a>
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js" type="text/javascript"></script>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

<script type="text/javascript">
  var CastPlayer = new CastPlayer();

  var mediaJSON =
  { "categories" :
    [
    {
      "name" : "Movies",
      "videos" : [
      <%- Video.all.each do |video| %>
        {
          "description" : "",
          "sources" : [ "http://<%= Socket.ip_address_list.detect{|intf| intf.ipv4_private?}.ip_address %>:8080/movies/<%= video.path.identifier! %>" ],
          "subtitle" : "",
          "thumb" : "http://<%= Socket.ip_address_list.detect{|intf| intf.ipv4_private?}.ip_address %>:8080/thumbs/<%= video.path.identifier!.split('.').first %>_thumb.jpg",
          "title" : "<i class='glyphicon glyphicon-film'></i> <%= video.path.identifier!.split('.').first.humanize %>"
        },
      <%- end %>
      ]
    }
    ]
  };
</script>

app/views/videos/index.html.slim
.m-mainwrapper.padding
  - if flash[:notice] || flash[:success]
    .container
      .alert.alert-success.alert-dismissable
        button.close aria-hidden="true" data-dismiss="alert" type="button"
        = "#{flash[:notice]} #{flash[:success]}"
  - if flash[:info]
    .container
      .alert.alert-info.alert-dismissable
        button.close aria-hidden="true" data-dismiss="alert" type="button"
        = flash[:info]
  - if flash[:error]
    .container
      .alert.alert-danger.alert-dismissable
        button.close aria-hidden="true" data-dismiss="alert" type="button"
        = flash[:error]

  .container.padding
    .row
      .col-lg-12
        h2.padding.black Manage your videos
        table.table.table-bordered.table-stripped
          thead
            tr
              th Video
              th Created at
              th
          tbody
            - @videos.each do |video|
              tr
                td
                  img src=('thumbs/' + video.path.identifier!.split('.').first + '_thumb.jpg') style="width:50px"
                  | &nbsp;
                  = video.path.identifier!.split('.').first
                td= l video.created_at, format: :short
                td
                  = link_to 'Delete', video, method: :delete, class: 'btn btn-danger', confirm: 'Really?'
        .col-lg-2
          = link_to 'Add a video', new_video_path, class: 'btn btn-success'
        .col-lg-2
          = link_to 'Back to homepage', root_path, class: 'btn btn-default'

app/views/videos/new.html.slim
.m-mainwrapper.padding
  .container.padding
    .row.padding
      .col-lg-12
        h2.black Upload your .mp4 video (this could take up yo 30sec/1min)
        h5 I am currently working on a avi/flv/mov to mp4 converter, stay tuned !
    .row.padding
      = simple_form_for @video  do |f|
        .col-lg-3
          = f.file_field :path
        .col-lg-3
          = f.submit 'Submit', class: 'btn btn-success'
    .row
      .col-lg-2
        = link_to 'Manage videos', videos_path, class: 'btn btn-default'
      .col-lg-2
        = link_to 'Back to homepage', root_path, class: 'btn btn-default'